package voteapplication;
/**
 * @author Monica
 *@datecreated 29 -Jul-2019
 */
/*Class definition to accept candidate details*/
public class Candidate 
{
   private int candidateId;/*variable for candidate id generated by admin*/
   private String candidateFirstName;
   private String candidateParty;
   private String city;
   private int age;
   private int count;/* variable for total number of candidates*/
   
   
  /*Method to store candidate details in database*/    
   public void candidateDetails(String candidateFirstName,String candidateParty,String city,int candidateId,int age)
     {
        this.candidateFirstName=candidateFirstName;
        this.candidateParty=candidateParty;
        this.city=city;
        this.candidateId=candidateId;
        this.age=age;
            
            //return checkVotersInDatabase(voterName,voterId,aadharNo,age);       
      }
   /*Method to check whether the candidate already exists in database or not*/
   public boolean checkCandidateInDatabase(int candidateId)
     {
         CandidateDbo cdo=new CandidateDbo();
        cdo.connectToDB();        
        if(cdo.getCandidateObjectById(candidateId)!=null)
            return true;
        return false;
     }     
   /* Method to retrieve candidate profile details
   format of retrival: CANDIDATEID | CANDIDATEFIRSTNAME | CANDIDATEPARTY | CITY | AGE */    
   public String showCandidateDetails()
     {
        return candidateId +"|"+ candidateFirstName +"|"+ candidateParty +"|"+ city +"|"+ age;
     }

   public void setCandidateId(int candidateId)
   {
       this.candidateId=candidateId;
   }
   
   public int getCandidateId()
   {
       return candidateId;
   }
   public void setCandidateFirstName(String candidateFirstName)
   {
       this.candidateFirstName=candidateFirstName;
   }
   
   public String getCandidateFirstName()
   {
       return candidateFirstName;
   }
   public void setCandidatePartyName(String candidateParty)
   {
       this.candidateParty=candidateParty;
   }
   
   public String getCandidatePartyName()
   {
       return candidateParty;
   }
   public void setCandidateLocation(String location)
   {
       this.city=location;
   }
   public String getCandidateLocation()
   {
       return city;
   }
   public void setCandidateAge(int age)
   {
       this.age=age;
   }
   
   public int getCandidateAge()
   {
       return age;
   }

}

            