package voteapplication;
/**
 * @author Monica
 *@datecreated 29 -Jul-2019
 */
/*Class definition to accept candidate details*/
public class Candidate 
{
   private String candidateFirstName;
   private String candidateParty;
   private int candidateId;/*variable for candidate id generated by admin*/
   private int age;
   private int count;/* variable for total number of candidates*/
   private String city;
   
  /*Method to store candidate details in database*/    
   public void candidateDetails(String candidateFirstName,String candidateParty,String city,int candidateId,int age)
     {
        this.candidateFirstName=candidateFirstName;
        this.candidateParty=candidateParty;
        this.city=city;
        this.candidateId=candidateId;
        this.age=age;
            
            return checkVotersInDatabase(voterName,voterId,aadharNo,age);
      }
   /*Method to check whether the candidate already exists in database or not*/
   public boolean checkCandidateInDatabase(int candidateId)
     {
        if(this.candidateId==candidateId)
            return true;
           return false;
     }     
   /* Method to retrieve candidate profile details
   format of retrival: CANDIDATEID | CANDIDATEFIRSTNAME | CANDIDATEPARTY | CITY | AGE */    
   public String showCandidateDetails()
     {
        return candidateId +"|"+ candidateFirstName +"|"+ candidateParty +"|"+ city +"|"+ age;
     }
   public void setCandidateId(int candidateId)
   {
       this.candidateId=candidateId;
   }
   
   public int getCandidateId()
   {
       return candidateId;
   }
   public void setCandidateFirstName(String candidateFirstName)
   {
       this.candidateFirstName=candidateFirstName;
   }
   
   public String getCandidateFirstName()
   {
       return candidateFirstName;
   }
   public void setCandidateParty(String candidateParty)
   {
       this.candidateParty=candidateParty;
   }
   
   public String getCandidateParty()
   {
       return candidateParty;
   }
   public void setCity(String city)
   {
       this.city=city;
   }
   public String getCity()
   {
       return city;
   }
   public void setAge(int age)
   {
       this.age=age;
   }
   
   public int getage()
   {
       return age;
   }

}

            