package voteapplication;
/**
 * @author Monica
 *@datecreated 27-Jul-2019
 */
/* Class definition to cast the vote from voter*/
public class CastVote 
{
  private int candidateId;/* variable candidate id generated by admin*/
  private int voterId;/* variable voter id give by government*/
  /* Method to accept candidate Id*/
  public int getcandidateId()
   { 
     voteapplication.Candidate obj=new voteapplication.Candidate();
     return candidateId;
   }
  /*Method to accept voter Id*/
  public int getvoterId()
   {
     voteapplication.VoterRole obj=new voteapplication.VoterRole();
     return voterId;
   }
}
    

